# Generated by Django 5.0.6 on 2026-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('sumber', models.CharField(max_length=50)),
                ('teks', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_base/')),
                ('status', models.SmallIntegerField(default=1)),
                ('processing_status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('done', 'Selesai'), ('failed', 'Gagal'), ('needs_ocr', 'Butuh OCR')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_bases', to='master_data.masterguru')),
            ],
            options={
                'db_table': 'knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='KbChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'kb_chunks',
                'ordering': ['knowledge_base_id', 'chunk_index'],
                'unique_together': {('knowledge_base', 'chunk_index')},
            },
        ),
    ]
