# Generated by Django 5.0.6 on 2026-09-15 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJurusan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Nonaktif'), (1, 'Aktif')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_jurusan', models.CharField(max_length=20, unique=True)),
                ('nama_jurusan', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_jurusan',
            },
        ),
        migrations.CreateModel(
            name='MasterKelas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Nonaktif'), (1, 'Aktif')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=100)),
                ('tingkat', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'master_kelas',
            },
        ),
        migrations.CreateModel(
            name='MasterGuru',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Nonaktif'), (1, 'Aktif')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guru_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_guru',
            },
        ),
        migrations.CreateModel(
            name='MasterSiswa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Nonaktif'), (1, 'Aktif')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='master_data.masterjurusan')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='master_data.masterkelas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_siswa',
            },
        ),
    ]
