# Generated by Django 5.0.6 on 2026-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semantic_raw', models.FloatField(blank=True, null=True)),
                ('semantic_score', models.FloatField(blank=True, null=True)),
                ('concept_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('relevance_status', models.CharField(blank=True, default='', max_length=20)),
                ('text_quality_status', models.CharField(blank=True, default='', max_length=20)),
                ('noise_penalty_applied', models.BooleanField(default=False)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('scoring_version', models.CharField(blank=True, default='', max_length=20)),
                ('processing_status', models.CharField(choices=[('success', 'Berhasil'), ('failed', 'Gagal Diproses')], default='success', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jawaban', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='penilaian', to='answers.jawaban')),
            ],
            options={
                'db_table': 'penilaian',
            },
        ),
        migrations.CreateModel(
            name='PenilaianConceptUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('detected', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.conceptunit')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_cu', to='scoring.penilaian')),
            ],
            options={
                'db_table': 'penilaian_concept_unit',
                'unique_together': {('penilaian', 'concept_unit')},
            },
        ),
    ]
