# Generated by Django 5.0.6 on 2026-09-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian',
            name='top_k_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]