# Generated by Django 5.0.6 on 2026-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Nonaktif'), (1, 'Aktif')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pertanyaan', models.TextField()),
                ('jawaban_acuan', models.TextField(blank=True, default='')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soal_list', to='master_data.masterguru')),
            ],
            options={
                'db_table': 'soal',
            },
        ),
        migrations.CreateModel(
            name='ConceptUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('konsep', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('bobot', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_units', to='questions.soal')),
            ],
            options={
                'db_table': 'concept_units',
                'ordering': ['soal_id', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='SoalKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge_base.knowledgebase')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.soal')),
            ],
            options={
                'db_table': 'soal_knowledge_base',
                'unique_together': {('soal', 'knowledge_base')},
            },
        ),
        migrations.AddField(
            model_name='soal',
            name='knowledge_bases',
            field=models.ManyToManyField(related_name='soal_list', through='questions.SoalKnowledgeBase', to='knowledge_base.knowledgebase'),
        ),
    ]
