# Generated by Django 5.0.6 on 2026-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UjianSoal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ujian_soal',
                'ordering': ['ujian_id', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_ujian', models.CharField(max_length=255)),
                ('jenis_ujian', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('selesai', 'Selesai')], default='aktif', max_length=20)),
                ('hasil_published', models.BooleanField(default=False)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ujian_list', to='master_data.masterguru')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ujian_list', to='master_data.masterjurusan')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ujian_list', to='master_data.masterkelas')),
            ],
            options={
                'db_table': 'ujian',
            },
        ),
    ]
