# Generated by Django 5.0.6 on 2026-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujiansoal',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.soal'),
        ),
        migrations.AddField(
            model_name='ujiansoal',
            name='ujian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.ujian'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='soal_list',
            field=models.ManyToManyField(related_name='ujian_list', through='exams.UjianSoal', to='questions.soal'),
        ),
        migrations.AlterUniqueTogether(
            name='ujiansoal',
            unique_together={('ujian', 'soal')},
        ),
        migrations.AddConstraint(
            model_name='ujian',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aktif')), fields=('token',), name='uniq_token_ujian_aktif'),
        ),
    ]
