# Generated by Django 5.0.6 on 2026-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawaban',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jawaban_set', to='questions.soal'),
        ),
        migrations.AddField(
            model_name='jawaban',
            name='ujian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jawaban_set', to='exams.ujian'),
        ),
        migrations.AddConstraint(
            model_name='jawaban',
            constraint=models.UniqueConstraint(fields=('ujian', 'siswa', 'soal'), name='uniq_jawaban_ujian_siswa_soal'),
        ),
    ]
